prometheus:
  enabled: true

server:
  name: server
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    storageClass: gp2

alertmanager:
  persistence:
    storageClass: gp2
