loki:
  commonConfig:
    replication_factor: 3
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    aws:
      region: us-west-2
      bucketnames: loki-log-chunks-2tci08 
      s3forcepathstyle: false
  pattern_ingester:
      enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 672h # 28 days retention

  storage:
    type: s3
    bucketNames:
        chunks: loki-log-chunks-2tci08
        ruler: loki-alert-rules-2tci08

deploymentMode: SingleBinary

singleBinary:
  replicas: 2
  persistence:
    storageClass: gp2
    accessModes:
      - ReadWriteOnce
    size: 3Gi

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

serviceAccount:
  ##create: true
  ##name: loki
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::905418146175:role/loki-service-account-role 
