apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  index.html: |
    {{- .Files.Get "files/index.html" | nindent 4 }}

  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /metrics {
            stub_status;
            allow 10.0.0.0/24
        }
    }
