exporters:
  loki:
    endpoint: "http://loki.loki.svc.cluster.local:3100/loki/api/v1/push"
    labels:
      namespace: alloy
      job: alloy-logs

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [loki]
