alloy:
  configMap:
    create: true
    content: |
      loki.write "default" {
        endpoint {
          url       = "http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push"
          tenant_id = "tenant1"
        }
        external_labels = {}
      }

      loki.source.kubernetes "homelab" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [loki.write.default.receiver]
      }
      
      logging {
        level  = "debug"
        format = "logfmt"
      }

      discovery.kubernetes "pods" {
        role = "pod"
      }
      
      discovery.kubernetes "nodes" {
        role = "node"
      }

