alloy:
  configMap:
    content: |
      loki.write "loki" {
        endpoint {
          url = "http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push"
        }
      }

      loki.source.kubernetes "default" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [loki.write.loki.receiver]
      }

      discovery.kubernetes "pods" {
        role = "pod"
      }

