alloy:
  configMap:
    content: |
      loki.write "default" {
        endpoint {
          url       = "http://loki-gateway.loki.svc.cluster.local"
          tenant_id = "tenant1"
        }
        external_labels = {}
      }

      loki.source.kubernetes "homelab" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [loki.write.default.receiver]
      }

      logging {
        level  = "debug"
        format = "logfmt"
      }

      discovery.kubernetes "pods" {
        role = "pod"
      }

      discovery.kubernetes "nodes" {
        role = "node"
      }

      discovery.kubernetes "services" {
        role = "service"
      }

      discovery.kubernetes "endpoints" {
        role = "endpoints"
      }

      discovery.kubernetes "endpointslices" {
        role = "endpointslice"
      }

      discovery.kubernetes "ingresses" {
        role = "ingress"
      }

